# Generated by Django 2.2.13 on 2020-06-23 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telegram_alias', models.CharField(max_length=30)),
                ('messenger_alias', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=30)),
                ('postal', models.IntegerField()),
                ('phone_number', models.CharField(max_length=30)),
            ],
        ),
    ]
