# Generated by Django 2.2.13 on 2020-07-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0003_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
